# Generated by Django 5.1.6 on 2026-03-07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usuarios", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="perfil",
            name="biografia",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="perfil",
            name="foto_perfil",
            field=models.ImageField(blank=True, null=True, upload_to="perfiles/"),
        ),
        migrations.AddField(
            model_name="perfil",
            name="foto_portada",
            field=models.ImageField(blank=True, null=True, upload_to="portadas/"),
        ),
        migrations.AddField(
            model_name="perfil",
            name="nombre_publico",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="perfil",
            name="telefono",
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
