# Generated by Django 5.1.6 on 2026-03-07 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='productos/')),
                ('descripcion', models.TextField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descuento', models.PositiveSmallIntegerField(default=0, help_text='Porcentaje 0-100')),
                ('envio_gratis', models.BooleanField(default=False)),
                ('stock', models.PositiveIntegerField(blank=True, null=True)),
                ('categoria', models.CharField(choices=[('ropa', 'Ropa'), ('calzado', 'Calzado'), ('accesorios', 'Accesorios'), ('otros', 'Otros')], default='otros', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
