# Generated by Django 5.1.6 on 2026-03-07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def migrar_categorias(apps, schema_editor):
    Producto = apps.get_model("productos", "Producto")
    Categoria = apps.get_model("productos", "Categoria")

    mapping = {
        "ropa": "Ropa",
        "calzado": "Calzado",
        "accesorios": "Accesorios",
        "otros": "Otros",
    }

    for old_value, nombre in mapping.items():
        Categoria.objects.get_or_create(nombre=nombre, defaults={"activo": True})

    for producto in Producto.objects.all():
        nombre_categoria = mapping.get(producto.categoria, "Otros")
        categoria = Categoria.objects.get(nombre=nombre_categoria)
        producto.categoria_nueva = categoria
        producto.save(update_fields=["categoria_nueva"])


class Migration(migrations.Migration):

    dependencies = [
        ("productos", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Categoria",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("nombre", models.CharField(max_length=80, unique=True)),
                ("activo", models.BooleanField(default=True)),
            ],
            options={"ordering": ["nombre"]},
        ),
        migrations.AddField(
            model_name="producto",
            name="vendedor",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="productos_publicados", to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name="producto",
            name="categoria_nueva",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="productos", to="productos.categoria"),
        ),
        migrations.RunPython(migrar_categorias, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name="producto",
            name="categoria",
        ),
        migrations.RenameField(
            model_name="producto",
            old_name="categoria_nueva",
            new_name="categoria",
        ),
        migrations.CreateModel(
            name="Pedido",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("total", models.DecimalField(decimal_places=2, max_digits=10)),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                (
                    "cliente",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="pedidos", to=settings.AUTH_USER_MODEL),
                ),
            ],
            options={"ordering": ["-fecha_creacion"]},
        ),
        migrations.CreateModel(
            name="PedidoItem",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("producto_nombre", models.CharField(max_length=120)),
                ("precio_unitario", models.DecimalField(decimal_places=2, max_digits=10)),
                ("cantidad", models.PositiveIntegerField(default=1)),
                ("subtotal", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "pedido",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="items", to="productos.pedido"),
                ),
            ],
        ),
    ]
