# Generated by Django 5.1.6 on 2026-03-07

from django.conf import settings
from django.db import migrations, models
import django.core.validators
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("productos", "0002_roles_categorias_pedidos"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Tienda",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("nombre", models.CharField(max_length=200)),
                ("descripcion", models.TextField(blank=True)),
                ("logo", models.ImageField(blank=True, null=True, upload_to="tiendas/")),
                ("whatsapp", models.CharField(max_length=20)),
                ("reputacion", models.FloatField(default=0)),
                ("calificacion", models.FloatField(default=0)),
                ("total_ventas", models.PositiveIntegerField(default=0)),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                ("activa", models.BooleanField(default=True)),
                (
                    "vendedor",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="tiendas", to=settings.AUTH_USER_MODEL),
                ),
            ],
            options={"ordering": ["-reputacion", "-calificacion", "nombre"]},
        ),
        migrations.AddField(
            model_name="producto",
            name="tienda",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="productos", to="productos.tienda"),
        ),
        migrations.AddField(
            model_name="pedido",
            name="tienda",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="pedidos", to="productos.tienda"),
        ),
        migrations.AddField(
            model_name="pedidoitem",
            name="producto",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="productos.producto"),
        ),
        migrations.CreateModel(
            name="ConsultaTienda",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("mensaje", models.TextField()),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                (
                    "tienda",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="consultas", to="productos.tienda"),
                ),
                (
                    "usuario",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="consultas_tienda", to=settings.AUTH_USER_MODEL),
                ),
            ],
            options={"ordering": ["-fecha_creacion"]},
        ),
        migrations.CreateModel(
            name="Favorito",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                (
                    "tienda",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="favoritos", to="productos.tienda"),
                ),
                (
                    "usuario",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="tiendas_favoritas", to=settings.AUTH_USER_MODEL),
                ),
            ],
            options={"unique_together": {("usuario", "tienda")}},
        ),
        migrations.CreateModel(
            name="Resena",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "estrellas",
                    models.PositiveSmallIntegerField(
                        validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]
                    ),
                ),
                ("comentario", models.TextField(blank=True)),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                (
                    "tienda",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="resenas", to="productos.tienda"),
                ),
                (
                    "usuario",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="resenas", to=settings.AUTH_USER_MODEL),
                ),
            ],
            options={"ordering": ["-fecha_creacion"], "unique_together": {("usuario", "tienda")}},
        ),
    ]
