# Generated by Django 5.1.6 on 2026-03-09 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0003_marketplace_tiendas'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('confirmado', 'Confirmado'), ('entregado', 'Entregado'), ('cancelado', 'Cancelado')], default='pendiente', max_length=20),
        ),
        migrations.AddField(
            model_name='producto',
            name='imagen_detalle',
            field=models.ImageField(blank=True, null=True, upload_to='productos/'),
        ),
        migrations.AddField(
            model_name='producto',
            name='imagen_secundaria',
            field=models.ImageField(blank=True, null=True, upload_to='productos/'),
        ),
        migrations.AddField(
            model_name='tienda',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to='tiendas/banner/'),
        ),
        migrations.AddField(
            model_name='tienda',
            name='color_tema',
            field=models.CharField(default='#0f766e', max_length=7),
        ),
        migrations.AddField(
            model_name='tienda',
            name='ubicacion',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
