# Generated by Django 5.1.6 on 2026-03-09 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0004_pedido_estado_producto_imagen_detalle_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='codigo_vendedor',
            field=models.CharField(blank=True, max_length=24, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('confirmado', 'Confirmado'), ('vendido', 'Vendido'), ('entregado', 'Entregado'), ('cancelado', 'Cancelado')], default='pendiente', max_length=20),
        ),
    ]
