# Generated by Django 5.1.6 on 2026-03-09 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0006_categoria_parent_seed_marketplace_categories'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoria',
            options={'ordering': ['parent__nombre', 'nombre']},
        ),
    ]
