# Generated by Django 5.1.6 on 2026-03-09 21:59

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0007_alter_categoria_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='imagen',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='imagen'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='imagen_detalle',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='imagen_detalle'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='imagen_secundaria',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='imagen_secundaria'),
        ),
    ]
