# Generated by Django 5.1.6 on 2026-03-09 22:52

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0008_alter_producto_imagen_alter_producto_imagen_detalle_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tienda',
            name='banner',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='banner'),
        ),
        migrations.AlterField(
            model_name='tienda',
            name='logo',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='logo'),
        ),
    ]
